package code;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.time.Instant;
import java.util.ArrayList;

public class LogGUI extends JFrame {
    private String path;
    JPanel contentPanel;
    JTextPane log;
    private File customDir;

    LogGUI() {
        setContentPane(contentPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setVisible(false);

        path = System.getProperty("user.home") + File.separator + "Documents";
        path += File.separator + "EtherChecker";
        customDir = new File(path);

    }

    void log(String string) {
        long timestamp = System.currentTimeMillis();
        Instant instant = Instant.ofEpochMilli(timestamp);

        log.setText(log.getText().concat("\n" + instant + string));

//        if (customDir.exists()) {
//            try {
//                saveToDisk(string);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        } else {
//            try {
//                createDirectory();
//                System.out.println("Directory created");
//                saveToDisk(string);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }

    private void createDirectory() throws Exception {
        if (!customDir.mkdirs()) {
            throw new Exception();
        }
    }

    private void saveToDisk(String text) throws IOException {

        File f = new File(path + File.separator + "log.txt");
        System.out.println(f);
        FileWriter fw = new FileWriter(f, false);
//        System.out.println(fw);

        try {
            BufferedWriter bw = new BufferedWriter(fw);
            System.out.println(text);

            bw.write(text);

            bw.flush();
            bw.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setAutoscrolls(false);
        contentPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        log = new JTextPane();
        log.setEditable(false);
        scrollPane1.setViewportView(log);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
